bc_format: bc1
bc_training:
  batch_res: 32
  betas:
  - 0.9
  - 0.999
  lr_feat: 0.01
  lr_mlp: 0.001
  total_iterations: 10
benchmark:
  mlp_param_bits: 16
  timing_iters: 1
  warmup_iters: 1
dataset:
  root: dataset
  target_res: 64
loss: l1
model:
  feature_configs:
  - - 64
    - 4
    - 3
  - - 32
    - 3
    - 3
  filter: trilinear
  half_pixel_offsets:
  - 1
  hidden_dim: 8
  num_layers: 1
uc_training:
  batch_res: 32
  gamma: 0.9995
  lr_feat: 0.05
  lr_mlp: 0.001
  total_iterations: 10
